### ISSUE TITLE
Create homepage

### ISSUE THREAD

**Issue by himanshu007-creator** [himanshu007-creator/SFC-foundations#112]
Create an alternate to homepage which is at present <a href="http://sfcfoundations.com/">this</a>
Use <a href="https://github.com/himanshu007-creator/SFC-foundations/tree/master/Design/Homepage">this</a> file to get the design

techstack:- HTML/CSS/JS only.

Deadline :- 10 days

requirements. Create page with transactions and stuff. You also need to add a theme toggler at the top of the page.
make your code in such manner that it can be used for other pages as well. For example the header, background, footer elements will remain same, so this is a very important issue.

**Comment by deeptea22** [comment]
Hey i would like to work on this issue. Please assign this to me as a part of GSSoC'21. Thank you :)

**Comment by CMELAKKIA** [comment]
Please assign me this issue as I can make good UI/UX design for your home page.

**Comment by SnehaVeerakumar** [comment]
> Please assign me this issue as I can make good UI/UX design for your home page.

I would be happy if @himanshu007-creator assigns @CMELAKKIA  this issue. As she is my best friend we can keep track of both frontend and backened and develop this project to next level. Also @CMELAKKIA is good in frontend part. I have worked with her personally in University projects 🙂 Just a suggestion @himanshu007-creator

**Comment by 1502shivam-singh** [comment]
Okay, instead of assigning randomly and creating a slug-fest for assignments, let's do something different this time.
Start working who wants to work. One who finishes earliest and has output nearest to the mockup in the deadline, will get the ticket.
Keep note of this thread while working, and whoever completes make a PR to this issue and tag us for faster response.

**And I would prefer this in general from now on from all participants**. **Do some work and show in issues** what you have done **to get yourself the ticket**. Vouching and just saying you want yourself to be assigned won't work, as then people stack up on issues and make them stale issues.

**Comment by himanshu007-creator** [comment]
> Please assign me this issue as I can make good UI/UX design for your home page.

Hi, we are asking to build to home page( code obviously ) designs are already there.

**Comment by 1502shivam-singh** [comment]
And @SAHU-01 could you put those images in a Figma board and share it. Going through a GitHub repository again and again would be cumbersome for others and then I can also leave exact comments based on elements in the design.

**Comment by himanshu007-creator** [comment]
> Okay, instead of assigning randomly and creating a slug-fest for assignments, let's do something different this time.
> Start working who wants to work. One who finishes earliest and has output nearest to the mockup in the deadline, will get the ticket.
> Keep note of this thread while working, and whoever completes make a PR to this issue and tag us for faster response.
> 
> **And I would prefer this in general from now on from all participants**. **Do some work and show in issues** what you have done **to get yourself the ticket**. Vouching and just saying you want yourself to be assigned won't work, as then people stack up on issues and make them stale issues.

Yes, proceed as mentioned.

**Comment by SAHU-01** [comment]
sure shivam I'll do that right away and i'll share the link here, so that the people who are going to work on the code can refer to it.

**Comment by SAHU-01** [comment]
here is the link to the figma project :

https://www.figma.com/proto/YzTe1JXho4W9DwcM2LLXRp/Untitled?node-id=16%3A34&frame-preset-name=Desktop&scaling=min-zoom&page-id=0%3A1

Let me know if the codeing team needs those same set of images that i've used , then i'll share those as well.

And i've kept it as view only mode so ,if somebody wishes to make edits let me know i'll exclusively give access to that person only.

**Comment by 1502shivam-singh** [comment]
I just left some comments, please check.
And if you are interested in coding the frontend part, do try this issue. Check my above comment for some background.

**Comment by SAHU-01** [comment]
Shivam for the logo, this is the 7th time I'd be changeing its size, its like once you tell me reduce it, himanshu asks me to increase it , so i guess it would be better if the three of us can go for a discord meeting and i'll share my screen live and make the logo and navbar sizeing their , so that once and for all we can fix the sizes.

Yup the textual format other than the "Be the change font " , we can change the style 

and the blue button on the extreme right coner is for the switch to dark theme , I was instructed to add a button for that so , I added it, If you have suggestion regarding that I'm all ears.

And except for the hero page ,I didn't find any other comments, let me know if you had comments on that , and for the hero I suggest lets hold a discord meetup !

For the codeing part ,I'd love doing that , but at present I'm stuck up with another Gssoc project mokup which has around 20 pages that i've to design so, according to what i understood from this issues above chats , the one who submits first their pr would be accepted so , maybe mine would be submitted after 4 days I guess.

I'll defenitely send the code from my side ,but lets see if I get assigned or my pr gets accepted :)

**Comment by subhasmitapradhan** [comment]
it would be great @SAHU-01 if you could share the link for images used. It would be easy for us to work.

**Comment by himanshu007-creator** [comment]
> Shivam for the logo, this is the 7th time I'd be changeing its size, its like once you tell me reduce it, himanshu asks me to increase it , so i guess it would be better if the three of us can go for a discord meeting and i'll share my screen live and make the logo and navbar sizeing their , so that once and for all we can fix the sizes.
> 
> Yup the textual format other than the "Be the change font " , we can change the style
> 
> and the blue button on the extreme right coner is for the switch to dark theme , I was instructed to add a button for that so , I added it, If you have suggestion regarding that I'm all ears.
> 
> And except for the hero page ,I didn't find any other comments, let me know if you had comments on that , and for the hero I suggest lets hold a discord meetup !
> 
> For the codeing part ,I'd love doing that , but at present I'm stuck up with another Gssoc project mokup which has around 20 pages that i've to design so, according to what i understood from this issues above chats , the one who submits first their pr would be accepted so , maybe mine would be submitted after 4 days I guess.
> 
> I'll defenitely send the code from my side ,but lets see if I get assigned or my pr gets accepted :)

you can discuss all details with @1502shivam-singh , but KEEP THE LOGO medium sized, not small

**Comment by SAHU-01** [comment]
/cc @1502shivam-singh  Lets set up a meet up then, do let me know when you are free

/cc @subhasmitapradhan  and other participants here is the folder with all images, and for the planet photograph thing you can head on to canva it provides a photograph frame in the elements selction, if any of you still find it difficult to make those photograph type of things for hero caroursel or need any design help for this webpage let me know I'll help you with them .


[ezyzip (1).zip](https://github.com/himanshu007-creator/SFC-foundations/files/6228346/ezyzip.1.zip)

**Comment by 1502shivam-singh** [comment]
> Shivam for the logo, this is the 7th time I'd be changeing its size, its like once you tell me reduce it, himanshu asks me to increase it , so i guess it would be better if the three of us can go for a discord meeting and i'll share my screen live and make the logo and navbar sizeing their , so that once and for all we can fix the sizes.
> 
> Yup the textual format other than the "Be the change font " , we can change the style
> 
> and the blue button on the extreme right coner is for the switch to dark theme , I was instructed to add a button for that so , I added it, If you have suggestion regarding that I'm all ears.
> 
> And except for the hero page ,I didn't find any other comments, let me know if you had comments on that , and for the hero I suggest lets hold a discord meetup !
> 
> For the codeing part ,I'd love doing that , but at present I'm stuck up with another Gssoc project mokup which has around 20 pages that i've to design so, according to what i understood from this issues above chats , the one who submits first their pr would be accepted so , maybe mine would be submitted after 4 days I guess.
> 
> I'll defenitely send the code from my side ,but lets see if I get assigned or my pr gets accepted :)

Okay then, I understand. Let it the circular thing in logo stay as it is for now, while I discuss. 
No need for a meet for now I suppose, I will tell when its needed don't worry.

**Comment by 1502shivam-singh** [comment]
> > Shivam for the logo, this is the 7th time I'd be changeing its size, its like once you tell me reduce it, himanshu asks me to increase it , so i guess it would be better if the three of us can go for a discord meeting and i'll share my screen live and make the logo and navbar sizeing their , so that once and for all we can fix the sizes.
> > Yup the textual format other than the "Be the change font " , we can change the style
> > and the blue button on the extreme right coner is for the switch to dark theme , I was instructed to add a button for that so , I added it, If you have suggestion regarding that I'm all ears.
> > And except for the hero page ,I didn't find any other comments, let me know if you had comments on that , and for the hero I suggest lets hold a discord meetup !
> > For the codeing part ,I'd love doing that , but at present I'm stuck up with another Gssoc project mokup which has around 20 pages that i've to design so, according to what i understood from this issues above chats , the one who submits first their pr would be accepted so , maybe mine would be submitted after 4 days I guess.
> > I'll defenitely send the code from my side ,but lets see if I get assigned or my pr gets accepted :)
> 
> you can discuss all details with @1502shivam-singh , but KEEP THE LOGO medium sized, not small

But why exactly @himanshu007-creator? If its told to you from the foundation's side then ya it makes sense, can't really help it then (well, actually can be done if you discuss with them what I am going to write below, but its your choice). But if not then I really want to know the reason for it to stay as is.
You see, the circle in the logo (I mean "circle+text") overflows the text baseline in the logo abnormally, and anyway the "SFC foundation" text in logo is not compatible with the text because of relative size differences. For a visual example consider unity's logo and then the foundation's logo, you will understand what I mean.
![image](https://user-images.githubusercontent.com/57267960/112979902-d0316a80-9176-11eb-8268-a648a1ff678d.png)
![image](https://user-images.githubusercontent.com/57267960/112980050-ffe07280-9176-11eb-819d-f1545b785a10.png)

If it's really from the foundation side, then @SAHU-01 I would prefer at least center the text in the logo vertically, so that the mid-line between the the text in the logo aligns with the center of the circle in the logo.

**Comment by CMELAKKIA** [comment]
Within three days I have coded for the following output. Before SFC FOUNDATIONS, I will add logo once it is finalized. Kindly assign me this issue so that I can confidently proceed with my works for home page.
![SFC frontend](https://user-images.githubusercontent.com/76167557/113337214-19cfb000-9345-11eb-82d4-7c86729bf01a.jpeg)

**Comment by deeptea22** [comment]
hey @1502shivam-singh @himanshu007-creator  This is my progress so far(the footer still needs to be completed), based on the design you have provided. 
Will be finishing the remaining parts soon. 
![Screenshot (238)](https://user-images.githubusercontent.com/67323371/113381511-c2f5c500-939c-11eb-88dc-a3313e76b950.png)
![Screenshot (239)](https://user-images.githubusercontent.com/67323371/113381520-c8530f80-939c-11eb-9247-e455f8c6a6f0.png)

**Comment by mansijain980** [comment]
@himanshu007-creator i want to use carousel in it .with some attractive ideas . Please assign it to me.

**Comment by 1502shivam-singh** [comment]
> Within three days I have coded for the following output. Before SFC FOUNDATIONS, I will add logo once it is finalized. Kindly assign me this issue so that I can confidently proceed with my works for home page.
> ![SFC frontend](https://user-images.githubusercontent.com/76167557/113337214-19cfb000-9345-11eb-82d4-7c86729bf01a.jpeg)

@CMELAKKIA good work, but this is not in accordance with the design that was proposed. Please refer to Figma link mentioned in above comments for the proposed mockup.
You can either work on modifying this to match the proposed design or wait for sometime until we have some base code to work on. You (as well as others) can then work on modifying this base code structure to bring changes to the existing design, as there is still a lot of scope of improvement in the current design.

**Comment by 1502shivam-singh** [comment]
> hey @1502shivam-singh @himanshu007-creator This is my progress so far(the footer still needs to be completed), based on the design you have provided.
> Will be finishing the remaining parts soon.
> ![Screenshot (238)](https://user-images.githubusercontent.com/67323371/113381511-c2f5c500-939c-11eb-88dc-a3313e76b950.png)
> ![Screenshot (239)](https://user-images.githubusercontent.com/67323371/113381520-c8530f80-939c-11eb-9247-e455f8c6a6f0.png)

Good work @deeptea22, proceed to create other sections.

**Comment by 1502shivam-singh** [comment]
> @himanshu007-creator i want to use carousel in it .with some attractive ideas . Please assign it to me.

@mansijain980, please clarify where you want to use carousel, using some mockups if possible. 
Currently we are focusing or creating a base code structure according to design proposed by one of the participants (Link to mockup in above comments) 
If you want to you can start by working on coding this design and sharing your work in this thread when completed to some extent, so that we can review your work.
Otherwise, wait until we have some base code to edit. Then you and all participants can contribute to this code by modifying design, adding sections etc. as there is still scope of improvement.

**Comment by SAHU-01** [comment]
> @himanshu007-creator i want to use carousel in it .with some attractive ideas . Please assign it to me.

Hi mansi there are 3 carousel used already  in my design , if you go through the design , there is also an accordian carousal apart from the genearally used carousals.

**Comment by SahityaRoy** [comment]
> Create an alternate to homepage which is at present [this](http://sfcfoundations.com/)
> Use [this](https://github.com/himanshu007-creator/SFC-foundations/tree/master/Design/Homepage) file to get the design
> 
> techstack:- HTML/CSS/JS only.
> 
> Deadline :- 10 days
> 
> requirements. Create page with transactions and stuff. You also need to add a theme toggler at the top of the page.
> make your code in such manner that it can be used for other pages as well. For example the header, background, footer elements will remain same, so this is a very important issue.

SIR I WANT TO CONTRIBUTE PLEASE ASSIGN ME  THIS TASK

**Comment by mansijain980** [comment]
@himanshu007-creator sir i want to contribute in this and create attractive  homepage from beginning.
PLease assign it to me.
Thanks.

**Comment by 1502shivam-singh** [comment]
> Okay, instead of assigning randomly and creating a slug-fest for assignments, let's do something different this time.
> Start working who wants to work. One who finishes earliest and has output nearest to the mockup in the deadline, will get the ticket.
> Keep note of this thread while working, and whoever completes make a PR to this issue and tag us for faster response.
> 
> **And I would prefer this in general from now on from all participants**. **Do some work and show in issues** what you have done **to get yourself the ticket**. Vouching and just saying you want yourself to be assigned won't work, as then people stack up on issues and make them stale issues.

Please read this 👆 and this 👇 if you want to contribute


> > @himanshu007-creator i want to use carousel in it .with some attractive ideas . Please assign it to me.
> 
> @mansijain980, please clarify where you want to use carousel, using some mockups if possible.
> Currently we are focusing or creating a base code structure according to design proposed by one of the participants (Link to mockup in above comments)
> If you want to you can start by working on coding this design and sharing your work in this thread when completed to some extent, so that we can review your work.
> Otherwise, wait until we have some base code to edit. Then you and all participants can contribute to this code by modifying design, adding sections etc. as there is still scope of improvement.


And @deeptea22 how's your progress, make a PR when you are done, and tag me for a review.

**Comment by deeptea22** [comment]
@1502shivam-singh I'm almost done (90% finished) I will do the PR by today or tomorrow. Thanks :)
